#ifndef DEFINES_IOCTL_H
#define DEFINES_IOCTL_H

#define MODULE_NAME "armadillo"
#define PKPRE "[" MODULE_NAME "] "

#define ARMADILLO_MAX_PASS_LENGTH 15
#define ARMADILLO_MAX_PASS_LENGTH_TERMINATED ARMADILLO_MAX_PASS_LENGTH + 1

#define ARMADILLO_POLICY_PATH_MAX 512
#define ARMADILLO_POLICY_COMM_LEN 16

#define INIT_WITH_DEBUG 1
#define INSTALL_HOOKS_ON_INIT 1

#define ARMADILLO_CLASS "armadillo"
#define ARMADILLO_CLASS_DRIVER "armadillo_cdrv"
#define ARMADILLO_DEVICE_FILE_NAME "/dev/armadillo_cdrv"
#define ARMADILLO_IOCTL_SUCCESS 0

#define ARMADILLO_LOCKED_MESSAGE "LOCKED... You shall not pass!!!"

#endif // DEFINES_IOCTL_H
